## To use this environment file with Anaconda Python: conda env create -f environment.yml -p ./env
## To activate the environment: conda activate ./env

channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - numpy
  - cftime
  - pandas
  - plotly
  - dash
  - dash-bootstrap-components
  - colorcet
